# Generated by Django 3.2.9 on 2021-12-24 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
